Task 2. Post component
Skilsar/iTechArt-StudentLab pull request #23
Opened 2023-07-07 17:00 UTC by Skilsar

# Overview
Assignments Task 2. Post component

# Changes
- Added project structure;
- Developed Layout;
- Developed Post component.

2023-07-08 19:09 UTC, dapodev commented on src/App.tsx
> +import { ConfigProvider } from 'antd';
Please, fix the imports

2023-07-08 19:10 UTC, dapodev commented on src/components/DefaultLayout/DefaultLayout.tsx
> +import { StyledContent, StyledContentLayout } from './styled';
Fix imports

2023-07-08 19:11 UTC, dapodev commented on src/App.tsx
>  function App(): JSX.Element {
make app component using arrow function

2023-07-08 19:11 UTC, dapodev commented on src/components/DefaultLayout/DefaultLayout.tsx
> +    <Navigate></Navigate>
If nothing is placed inside component, you should use that kind of notation: `<Component />`

2023-07-08 19:12 UTC, dapodev commented on src/components/DefaultLayout/styled.ts
> +const { Content } = Layout;
Import section should not contain any desctructuring

2023-07-08 19:12 UTC, dapodev commented on src/components/DefaultLayout/styled.ts
> +import styled from 'styled-components';
Mess in imports, fix it

2023-07-08 19:12 UTC, dapodev commented on src/components/DefaultLayout/styled.ts
> +  // Style for block without background
Are these comment a necessity ?

2023-07-08 19:13 UTC, dapodev commented on src/components/Footer/Footer.tsx
> +    <div className='copyright'>
Don't use `className`s please

2023-07-08 19:13 UTC, dapodev commented on src/components/Footer/styled.ts
> +import { Footer } from 'antd/es/layout/layout';
Fix imports

2023-07-08 19:14 UTC, dapodev commented on src/components/Navigate/Navigate.tsx
> +import { Layout, Menu } from 'antd';
fix imports

2023-07-08 19:15 UTC, dapodev commented on src/components/Navigate/Navigate.tsx
> +        <StyledMenuItem key='1'>All Users</StyledMenuItem>
Extract Menu items to constant and render them using `map` and use `index` as key

2023-07-08 19:15 UTC, dapodev commented on src/components/Navigate/styled.ts
> +const { Header } = Layout;
same with import section

2023-07-08 19:16 UTC, dapodev commented on src/components/Navigate/styled.ts
> +import { COLORS } from '../../config/colors';
your imports should not have more than one level of relative path `back-linking`, no `../../../component` should be used, only `../component` allowed

2023-07-08 19:17 UTC, dapodev commented on src/components/Navigate/styled.ts
> +  left: '0',
Don't use `relative` positioning without particular reason, fix it

2023-07-08 19:17 UTC, dapodev commented on src/components/Navigate/styled.ts
> +  paddingInline: '0',
All the styled parameters should be numbers if no postfixes required
`padding: 0` but `padding: '22px`

2023-07-08 19:18 UTC, dapodev commented on src/components/Navigate/styled.ts
> +  left: '0',
Fix please among all the app so not to cope pasting comments

2023-07-08 19:18 UTC, dapodev commented on src/components/Posts/Posts.tsx
> +import { Layout } from 'antd';
Fix imports

2023-07-08 19:19 UTC, dapodev commented on src/components/Posts/Posts.tsx
> +            {!post.removed && (
removed posts should not be passed to front-end application, backend should exclude it from response itself

2023-07-08 19:20 UTC, dapodev commented on src/components/Posts/Posts.tsx
> +        const isCommentExists = post.commentsAmount > 0;
```suggestion
        const isCommentsExists = post.commentsAmount > 0;
```

2023-07-08 19:20 UTC, dapodev commented on src/components/Posts/components/Post.tsx
> +const Post: React.FC<IPostComponent> = ({
```suggestion
const Post: FC<IPostComponent> = ({
```
Fix please among all the app

2023-07-08 19:20 UTC, dapodev commented on src/components/Posts/components/Post.tsx
> +    {/* Блок комментариев */}
What is it for?

2023-07-08 19:22 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +import styled from 'styled-components';
Fix imports

2023-07-08 19:23 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +const PostContainer = styled('div')({
Don't use `container` word in styled components naming, please
That gonna confuse developers, cause we're using `Container` components approach. So `container` should be a "smart" part of a component, but not a styled component. Use for example `PostWrapper`

2023-07-08 19:24 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +  padding: '10px 20px 5px 20px',
```suggestion
  padding: '10px 20px 5px',
```
That is the same

2023-07-08 19:24 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +  color: COLORS.TEXT_LIGHT,
Please, make it right order

2023-07-08 19:24 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +  padding: '10px 20px 5px 20px',
Order

2023-07-08 19:24 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +  marginBottom: '20px',
Order

2023-07-08 19:25 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +  marginLeft: '15px',
Please, fix all the styles orders among the app so that I don't copy paste comments

2023-07-08 19:25 UTC, dapodev commented on src/components/Posts/components/styled.ts
> +
Don't use empty styled components

2023-07-08 19:27 UTC, dapodev commented on src/components/Posts/types.ts
> +export interface IPost {
Don't you think we should extract this to common types folder? Will we use this type somewhere outside this component?

2023-07-08 19:27 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +      defaultOpenKeys={['sub1']}
Magic strings

2023-07-08 19:27 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +      <StyledMenuItem key='5'>Exit</StyledMenuItem>
use `.map` and some kind of config constant

2023-07-08 19:27 UTC, dapodev commented on src/components/Sidebar/styled.ts
> +import { Layout, Menu } from 'antd';
imports..

2023-07-08 19:28 UTC, dapodev commented on src/components/Sidebar/styled.ts
> +  // height: '100%',
Comment

2023-07-08 19:28 UTC, dapodev commented on src/config/colors.ts
> +  POST_BORDER = '#ebeef4',
all these keys should be lowercased

2023-07-08 19:29 UTC, dapodev commented on src/config/default-style.ts
> +  BORDER_RADIUS = '5px',
lowercase

2023-07-08 19:29 UTC, dapodev commented on src/config/theme-config.ts
> +import { ThemeConfig } from 'antd';
imports

2023-07-08 19:29 UTC, dapodev commented on src/config/theme-config.ts
> +  // },
comments

2023-07-08 19:29 UTC, dapodev commented on src/styled.ts
> +import { createGlobalStyle } from 'styled-components';
imports

2023-07-11 16:13 UTC, dapodev requested changes
1. Fix kebab-cased file names to camelCase
2. Only component file names can start with uppercase, not type files (`IPostProps.ts`)
3. Styles order is not following provided during html/css course rules. Fix it
4. Each Component should have its own folder, its own index.ts file (which gonna export some component as default for the entire folder, e.g. component's container or component itself), its own styled and types file if needed. Eg: 
<img width="441" alt="image" src="https://github.com/Skilsar/iTechArt-StudentLab/assets/70802978/da8de049-b977-4cb5-b664-c2ef0d3763a1">

5. Pages and components are not the same thing. `Posts` - is a page, and should be declared  somewhere in `src/pages/Posts` folder! `Post` - is a component, and it should be stored somewhere in `src/components/Post` if it is used among several pages/components or in `src/pages/Posts/components/Post` folder if it's used only within `Posts` page
6. Please, use separate `constants.ts` file for constants, don't mesh up the components with extracted constants

2023-07-11 16:13 UTC, dapodev commented on src/components/Posts/components/types.ts
> +export interface IPostComponent {
```suggestion
export interface IPostComponentProps {
```
`Props` Postfix will help you to recognise props-types

2023-07-11 16:13 UTC, dapodev commented on src/components/Posts/styled.ts
> +export const PageWrapper = styled.div`
Why do you mix both different `export` style and `styled-components` declarations?
1. `export const Component` and `const Component... export { Component };`
2. `styled('div')` and `styled.div`
Please, choose one style for all the project in both examples

2023-07-11 16:13 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +const menuItems = [
immutable constant

2023-07-11 16:13 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +const defaultMenuItem = '1';
immutable constant

2023-07-11 16:13 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +  { key: '2', title: 'My Posts' },
Do we need these keys or `index` value would be enough?

2023-07-11 16:13 UTC, dapodev commented on src/components/Sidebar/Sidebar.jsx
> +      <Avatar size={64} icon={<UserOutlined />} />
You gonna use this component in several different places, so please, extract this to another component or provide constant to `64` magic number

2023-07-11 16:13 UTC, dapodev commented on src/components/Sidebar/styled.ts
> +  margin: '0',
```suggestion
  margin: 0,
```

2023-07-11 16:13 UTC, dapodev commented on src/styled.ts
> +export const GlobalStyle = createGlobalStyle`
Common export style

2023-07-11 16:19 UTC, dapodev reviewed
And could you please mode `Add to bookmark` button somewhere to the top-right part of the component, and make it just an icon of bookmark (For now it's too standing out of the visual part of the component)
+ let's move author's section to the top-left part of the component and add authors avatar, not only name

2023-07-12 12:07 UTC, Skilsar commented on src/components/Navigate/styled.ts
> +  zIndex: '1000',
z-index is needed to display the menu (background and shadow) above other elements.

2023-07-12 12:30 UTC, Skilsar commented on src/styled.ts
> +export const GlobalStyle = createGlobalStyle`
Is it possible to use such export when exporting only one object?

2023-07-12 15:45 UTC, dapodev requested changes

2023-07-12 15:45 UTC, dapodev commented on src/components/index.ts
> +//delete this
!

2023-07-12 20:47 UTC, Skilsar commented on src/components/index.ts
> +//delete this
Fixed

2023-07-13 11:33 UTC, dapodev approved these changes

2023-07-13 11:34 UTC, merged