Task 3. React Routers
Skilsar/iTechArt-StudentLab pull request #25
Opened 2023-07-13 14:30 UTC by Skilsar

# Overview
Assignments Task 3. React routers

# Changes
- Added react router navigation in a project;
- Added 4 demo pages;
- Added demo navigation of pages.

# How to see
- GitHub Pages: https://skilsar.github.io/iTechArt-StudentLab/

2023-07-13 16:41 UTC, dapodev requested changes
Not found page logics is not working, please, visit [link](https://skilsar.github.io/iTechArt-StudentLab/not-found)

2023-07-13 16:41 UTC, dapodev commented on src/App.tsx
> +    <GlobalStyles />
Do we still need GlobalStyles?

2023-07-13 16:41 UTC, dapodev commented on src/components/Navigate/Navigate.tsx
> +const MENU_ITEMS = [
extract constant to another file

2023-07-13 16:41 UTC, dapodev commented on src/components/Navigate/Navigate.tsx
>  const DEFAULT_SELECTED_MENU_ITEM = '0';
And that one too

2023-07-13 16:41 UTC, dapodev commented on src/components/Title/Title.tsx
> +import { TitleProps } from 'types/titles/title';
Why this type is in global types folder? Props types are declared within component folder

2023-07-13 16:41 UTC, dapodev commented on src/pages/Error/Error.tsx
> +import NotFound from 'assets/images/not-found.svg';
Could you please not import sag directly? you can declare index file inside assets/images folder and use that notation: 
`export { ReactComponent as NotFoundImage } from './not-found.svg';`

2023-07-13 16:41 UTC, dapodev commented on src/pages/Error/Error.tsx
> +      <StyledButton href='/'>Back to home</StyledButton>
Magic string

2023-07-13 16:41 UTC, dapodev commented on src/pages/Posts/Posts.tsx
> +const POSTS = [
to constants file

2023-07-13 16:41 UTC, dapodev commented on src/pages/SignIn/styled.ts
> +  background: COLORS.background,
Styles order!!!!!! Please, Fix all over the PR

2023-07-13 16:41 UTC, dapodev commented on src/router/router.tsx
> +import { Navigate, Route, Routes } from 'react-router-dom';
Filename has lowercase

2023-07-13 16:41 UTC, dapodev commented on src/router/routes.ts
> +export enum ROUTE {
Enum constants should not be UPPERCASED

2023-07-13 16:41 UTC, dapodev commented on src/router/router.tsx
> +import { Navigate, Route, Routes } from 'react-router-dom';
BTW this component is more like RouteList, but not a router. Could you please rename it?

2023-07-13 16:41 UTC, dapodev commented on src/router/router.tsx
> +        <Route path={ROUTE.main} element={<Navigate to={ROUTE.posts} />} />
```suggestion
        <Route index element={<Navigate to={ROUTE.posts} />} />
```

2023-07-13 18:41 UTC, Skilsar commented on src/App.tsx
> +    <GlobalStyles />
Sori, I forgot)

2023-07-13 21:44 UTC, Skilsar commented
@dapodev, I fixed GitHub Pages

2023-07-15 20:58 UTC, dapodev requested changes
Not found page still doesn't work 😢

2023-07-15 21:03 UTC, dapodev requested changes

2023-07-15 21:03 UTC, dapodev commented on src/App.tsx
> +const BASE_REPO_NAME = '/iTechArt-StudentLab';
That should be provided using `.env`

2023-07-15 21:03 UTC, dapodev commented on src/pages/Error/styled.ts
> +  margin: '0 30px 0',
```suggestion
  margin: '0 30px',
```

2023-07-17 10:10 UTC, dapodev requested changes

2023-07-17 10:10 UTC, dapodev commented on src/App.tsx
> +const BASE_REPO_NAME = process.env.REACT_APP_BASE_REPO_NAME;
No validation for `env` variables? That's a bad practice

2023-07-17 12:16 UTC, merged